[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | venv
  | build

  # Orchest specific.
  | orchest/services/jupyter-server/patches
  | \.venvs
  | userdir
)/
'''

[tool.isort]
profile = "black"
filter_files = true
known_first_party = ["app", "_orchest", "orchest", "runner", "config"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88